export enum PrpgComponentType {
  TELEPORT = 'prpg.teleport',
  TELEPORTABLE = 'prpg.teleportable',
  PLAYER = 'prpg.player',
  CHARACTER = 'prpg.character',
  MAP = 'prpg.map',
  SPAWN_POINT = 'prpg.spawn-point',
  FADE_SCREEN = 'prpg.fade',
  BODY = 'prpg.body',
  MULTIPLAYER_SYNC = 'prpg.multiplayer-sync',
  SCREEN_POSITION = 'prpg.screen-position',
  SELECTABLE = 'prpg.selectable',
  ACTION = 'prpg.action',
  MENU_VISIBLE = 'prpg.menu-visible',
  CONTROLLABLE = 'prpg.controllable',
  MENU = 'prpg.menu',
  MENU_ITEM = 'prpg.menu-item',
  TEXT = 'prpg.text',
  TILEBOX = 'prpg.tilebox',
}