name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - "*"
jobs:
  # https://github.com/marketplace/actions/checkout-submodules
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        # uses: textbook/git-checkout-submodule-action@master
        run: git submodule update --init --recursive
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm install
      - name: Build each package
        run: |
          npm run build
      # - name: Lint each package
      #   run: |
      #     npm run lint
      # - name: Run tests for each package
      #   run: |
      #     npm run test